### ISSUE TITLE
 UnboundLocalError (showui_loop_count) on Windows + Python 3.12

### ISSUE THREAD

**Issue by bilbop1** [showlab/computer_use_ootb#62]
```
File "C:\Users\Razer Blade\computer_use_ootb\computer_use_demo\loop.py", line 217, in sampling_loop_sync
    print(f"End of loop {showui_loop_count+1}. Messages: ...
UnboundLocalError: cannot access local variable 'showui_loop_count' ...
```
Environment

OS: Windows 11, Razer Blade 2020, RTX 3060 (6 GB VRAM)
Python: 3.12.8
CUDA Driver: 560.94 (CUDA 12.6)
PyTorch: 2.5.1 (CUDA 12.4 build)

Crash with UnboundLocalError referencing showui_loop_count.

Would appreciate any guidance—others say it runs “out of the box,” but I keep getting this error on Windows + Python 3.12. Thanks!

**Comment by bilbop1** [comment]
Full Traceback
```Traceback (most recent call last):
  File "C:\Users\Razer Blade\miniconda3\Lib\site-packages\gradio\queueing.py", line 714, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Razer Blade\miniconda3\Lib\site-packages\gradio\route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Razer Blade\miniconda3\Lib\site-packages\gradio\blocks.py", line 2047, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Razer Blade\miniconda3\Lib\site-packages\gradio\blocks.py", line 1606, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Razer Blade\miniconda3\Lib\site-packages\gradio\utils.py", line 714, in async_iteration
    return await anext(iterator)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Razer Blade\miniconda3\Lib\site-packages\gradio\utils.py", line 708, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Razer Blade\miniconda3\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Razer Blade\miniconda3\Lib\site-packages\anyio\_backends\_asyncio.py", line 2505, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\Users\Razer Blade\miniconda3\Lib\site-packages\anyio\_backends\_asyncio.py", line 1005, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Razer Blade\miniconda3\Lib\site-packages\gradio\utils.py", line 691, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "C:\Users\Razer Blade\miniconda3\Lib\site-packages\gradio\utils.py", line 852, in gen_wrapper
    response = next(iterator)
               ^^^^^^^^^^^^^^
  File "C:\Users\Razer Blade\computer_use_ootb\app.py", line 273, in process_input
    for loop_msg in sampling_loop_sync(
                    ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Razer Blade\computer_use_ootb\computer_use_demo\loop.py", line 217, in sampling_loop_sync
    print(f"End of loop {showui_loop_count+1}. Messages: {str(messages)[:100000]}. Total cost: $USD{planner.total_cost:.5f}")
                         ^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'showui_loop_count' where it is not associated with a value
Keyboard interruption in main thread... closing server.```

**Comment by hkr04** [comment]
Add `showui_loop_count = 0` around line 127 (outside the loop) to set the initial value could simply fix that problem.

**Comment by Amaodemao** [comment]
> Add `showui_loop_count = 0` around line 127 (outside the loop) to set the initial value could simply fix that problem.

The method mentioned by @hkr04 works for me. But I tend to put the line at line 198 (right below the comment "Step 4: Output action message").

Thank you again!

PS: It seems like the performance of Qwen-vl is pretty questionable...

**Comment by ttuhin03** [comment]
could you maybe fix this error. @hkr04  Has the working solution
